---
AppName: MetaRefCard
Version: v0.2
DebugOutput: false
VerboseOutput: false
DevicesModel: config/generatedDevices.yaml
FontsDir: resources/fonts
InputFont: YanoneKaffeesatz-Regular.ttf
InputFontSize: 40
DefaultLineHeight: 54
InputPixelInset: 10
PixelMultiplier: 0.4
BackgroundColour: "#e9ecefff"
LightColour: "#ffffffff"
DarkColour: "#373a3cff"
AlternateColours:
  - "#2780e3ff" # Blue
  - "#ff0039ff" # Red
  - "#ff7518ff" # Orange
  - "#3fb618ff" # Green
  - "#9954bbff" # Purple
  - "#373a3cff" # Almost Black
  - "#2780e3a6" # Blue, lower opacity
  - "#ff0039a6" # Red, lower opacity
  - "#ff7518a6" # Orange, lower opacity
  - "#3fb618a6" # Green, lower opacity
  - "#9954bba6" # Purple, lower opacity
  - "#373a3ca6" # Almost Black, lower opacity
  # Blue: #2780e3;
  # Indigo: #6610f2;
  # Purple: #613d7c;
  # Pink: #e83e8c;
  # Red: #ff0039;
  # Orange: #f0ad4e;
  # Yellow: #ff7518;
  # Green: #3fb618;
  # Teal: #20c997;
  # Cyan: #9954bb;
  # White: #fff;
  # Gray: #868e96;
  # Gray-dark: #373a3c;
ImagesDir: resources/hotas_images
DefaultImageWidth: 3840
DefaultImageHeight: 2160
ImageSizeOverride:
  vkb-kosmosima-scg-left:
    Width: 3879
    Height: 2182
  x45:
    Width: 5120
    Height: 2880
...