---
AppName: MetaRefCard
Version: 0.2
DebugOutput: false
VerboseOutput: false

DevicesModel: config/generatedDevices.yaml
DeviceMap:
  ThrustMasterHOTAS4:
    14: { x: -1, y: -1, w: 592, h: 54 } # Does not exist
    15: { x: -1, y: -1, w: 592, h: 108 } # Does not exist
  ThrustMasterHOTASOne:
    1: { x: 1394, y: 614, w: 1082, h: 54 }
    2: { x: 2114, y: 264, w: 1192, h: 54 }
    3: { x: 2954, y: 544, w: 792, h: 108 }
    4: { x: 2754, y: 374, w: 832, h: 108 }
    5: { x: 950, y: 734, w: 592, h: 108 }
    6: { x: 950, y: 898, w: 592, h: 108 }
    7: { x: 950, y: 1046, w: 592, h: 108 }
    8: { x: 1044, y: 1374, w: 592, h: 108 }
    9: { x: 1628, y: 710, w: 832, h: 54 }
    10: { x: 1928, y: 790, w: 532, h: 108 }
    11: { x: 2073, y: 1642, w: 592, h: 108 }
    12: { x: 2192, y: 1785, w: 592, h: 108 }
    13: { x: 284, y: 2044, w: 592, h: 54 }
    14: { x: 984, y: 2044, w: 592, h: 54 }
    15: { x: 1216, y: 1676, w: 592, h: 108 }
    POV1Up: { x: 994, y: 354, w: 1532, h: 54 }
    POV1Right: { x: 994, y: 410, w: 1532, h: 54 }
    POV1Down: { x: 994, y: 466, w: 1532, h: 54 }
    POV1Left: { x: 994, y: 522, w: 1532, h: 54 }
    RZAxis: { x: 3018, y: 1988, w: 792, h: 108 }
    XAxis: { x: 3018, y: 1878, w: 792, h: 108 }
    YAxis: { x: 3018, y: 1768, w: 792, h: 108 }
    ZAxis: { x: 96, y: 736, w: 692, h: 54 }
    UAxis: { x: 1114, y: 1504, w: 932, h: 108 }
  ThrustMasterTFlightHOTASX:
    14: { x: -1, y: -1, w: 592, h: 54 } # Does not exist
    15: { x: -1, y: -1, w: 592, h: 108 } # Does not exist
InputOverrides:
  SaitekX55Throttle:
    1:     { x: 45,  y: 496, w: 852, h: 54 }
    35:    { x: 104, y: 416, w: 852, h: 54 }
    XAxis: { x: 166, y: 681, w: 570, h: 54 }
    YAxis: { x: 238, y: 588, w: 570, h: 54 }

ImageMap:
  ThrustMasterHOTASOne : hotasone
DefaultImage: { w: 3840, h: 2160 }
PixelMultiplier: 0.5
HotasImagesDir: resources/hotas_images
LogoImagesDir: resources/game_logos
ImageSizeOverride:
  vkb-kosmosima-scg-left: { w: 3879, h: 2182 }
  x45: { w: 5120, h: 2880 }
JpgQuality: 90

FontsDir: resources/fonts
InputFont: YanoneKaffeesatz-Regular.ttf
InputFontSize: 40
InputMinFontSize: 13
DefaultLineHeight: 54
InputPixelXInset: 5
InputPixelYInset: 5

ImageHeading:
  Font: Orbitron-Regular.ttf
  FontSize:  90
  Inset:
    x: 50
    y: 100
  TextHeight: 180
  TextColour: "#ffffffff"
  BackgroundHeight: 200
  BackgroundColour: "#2780e3ff"

Watermark:
  Text: MetaRefCard.com
  TextColour: "#ccccccff"
  Font: Dirga.ttf
  FontSize: 44
  Location:
    x: 50
    y: 170

BackgroundColour: "#e9ecefff"
LightColour: "#ffffffff"
DarkColour: "#373a3cff"
AlternateColours:
  - "#2780e3ff" # Blue
  - "#ff0039ff" # Red
  - "#ff7518ff" # Orange
  - "#3fb618ff" # Green
  - "#9954bbff" # Purple
  - "#373a3cff" # Almost Black
  - "#2780e3a6" # Blue, lower opacity
  - "#ff0039a6" # Red, lower opacity
  - "#ff7518a6" # Orange, lower opacity
  - "#3fb618a6" # Green, lower opacity
  - "#9954bba6" # Purple, lower opacity
  - "#373a3ca6" # Almost Black, lower opacity
  # Blue: #2780e3;
  # Indigo: #6610f2;
  # Purple: #613d7c;
  # Pink: #e83e8c;
  # Red: #ff0039;
  # Orange: #f0ad4e;
  # Yellow: #ff7518;
  # Green: #3fb618;
  # Teal: #20c997;
  # Cyan: #9954bb;
  # White: #fff;
  # Gray: #868e96;
  # Gray-dark: #373a3c;

DeviceToShortNameMap:
  # Airbus T-A320 Quadrant throttle:
  # Alpha Flight Controls:
  # BU0836X Interface:
  # BU0836X Interface_1:
  Joystick - HOTAS Warthog: ThrustMasterWarthogJoystick
  # Keyboard (FSX): # TODO Keyboad
  Logitech Extreme 3D: LogitechExtreme3DPro
  # Mouse: # TODO Mouse
  PS4: DualShock4
  # Saitek Pro Flight Quadrant:
  Saitek Pro Flight Rudder Pedals: SaitekProFlightCombatRudderPedals
  Saitek Pro Flight X-55 Rhino Stick: SaitekX55Joystick
  Saitek Pro Flight X-55 Rhino Throttle: SaitekX55Throttle
  Saitek Pro Flight X-56 Rhino Stick: SaitekX56Joystick
  Saitek Pro Flight X-56 Rhino Throttle: SaitekX56Throttle
  # Saitek Pro Flight Yoke:
  Saitek X52 Flight Control System: SaitekX52
  Saitek X52 Pro Flight Control System: SaitekX52Pro
  T.16000M: T16000M
  # T.A320 CoPilot:
  # T.A320 Pilot:
  T.Flight Hotas 4: ThrustMasterHOTAS4
  T.Flight Hotas One: ThrustMasterHOTASOne
  T.Flight Hotas X: ThrustMasterTFlightHOTASX
  T.Flight Rudder Pedals: T-Rudder
  T.Flight Stick X: 044FB106
  Throttle - HOTAS Warthog: ThrustMasterWarthogThrottle
  TWCS Throttle: T16000MTHROTTLE
  # T-Pendular-Rudder:
  # VF - TPM V3RNIO:
  # VirtualFly - RUDDO+:
  # VirtualFly - TQ3+:
  # VirtualFly - TQ6+:
  # VirtualFly - YOKO+:
  XInput Gamepad: GamePad
DeviceLabels:
  chcombat: "CH Combatstick & Throttle"
  chfighter: "CH Fighterstick & Throttle"
  chproflightquadrant: "CH Pro Flight Throttle Quadrant"
  chpropedals: "CH Pro Pedals"
  chquadrant: "CH Throttle Quadrant"
  cobram5: "Defender Cobra M5 Stick"
  cougar: "Cougar MFD"
  crosswind: "MFG Crosswind Pedals"
  ds4: "DualShock 4 Controller"
  extreme3dpro: "Extreme 3D Pro"
  f710: "F710 Controller"
  fly5: "Cyborg F.L.Y. 5 Stick"
  g940: "Logitech G940 Pedals"
  g940pedals: "G940 Stick & Throttle"
  gladiator: "VKB Gladiator"
  gtwheel: "Logitech Driving Force GT Wheel"
  hotas4: "T.Flight HOTAS 4 Stick & Throttle"
  hotascougar: "Thrustmaster Hotas Cougar"
  hotasone: "T.Flight HOTAS One Stick & Throttle"
  hotasx: "T.Flight HOTAS X Stick & Throttle"
  keyboard: "Keyboard"
  proflightcombatpedals: "Saitek Pro Flight Combat Pedals"
  proflightpedals: "Saitek Pro Flight Pedals"
  sabretooth: "Sabretooth Controller"
  sidepanelcontroldeck: "Side Panel Control Deck"
  slawbf109pedals: "Slaw BF-109 Pedals"
  stickx: "Thrustmaster T.Flight X Stick"
  t16000m: "T-16000M Stick"
  t16000mfcs: "T.16000M FCS Stick & Throttle"
  tfrp: "Thrustmaster T-Flight Pedals"
  vkb-kosmosima-scg-left: "VKB Kosmosima SCG Left"
  vkb-kosmosima-scg-right: "VKB Kosmosima SCG Right"
  vpc-warbrd-delta-left: "VPC WarBRD DELTA Left"
  vpc-warbrd-delta-right: "VPC WarBRD DELTA Right"
  warthog: "Warthog Stick & Throttle"
  x45: "X-45 Stick & Throttle"
  x52: "X-52 Pro Stick & Throttle"
  x52pro: "X-52 Stick & Throttle"
  x55: "X-55 Stick & Throttle"
  x56: "X-56 Stick & Throttle"
  xbox: "XBox Controller"
  xboxelite: "XBox Elite Controller"
...