---
GeneratedFile: config/generatedDevices.yaml
DeviceMap: # Extends generatedDevices.yaml
  AlphaFlight:
    1: { x: 165, y: 923, w: 800, h: 96 } # Trigger, left stick
    2: { x: 165, y: 806, w: 800, h: 96 } # Button left stick
    3: { x: 2940, y: 1328, w: 800, h: 96 } # Left button, right stick
    4: { x: 2940, y: 774, w: 800, h: 96 } # Right button, right stick
    5: { x: 165, y: 1143, w: 800, h: 96 } # Left switch down, left stick
    6: { x: 165, y: 1043, w: 800, h: 96 } # Left switch up, left stick
    7: { x: 165, y: 1363, w: 800, h: 96 } # Right swtich down, left stick
    8: { x: 165, y: 1263, w: 800, h: 96 } # Right switch up, left stick
    9: { x: 2940, y: 893, w: 800, h: 96 } # Top switch left, right stick
    10: { x: 2940, y: 993, w: 800, h: 96 } # Top switch right, right stick
    11: { x: 2940, y: 1110, w: 800, h: 96 } # Bottom switch left, right stick
    12: { x: 2940, y: 1210, w: 800, h: 96 } # Bottom switch right, right stick
    13: { x: 1092, y: 353, w: 600, h: 96 } # Master Alt up
    14: { x: -1, y: -1, w: 600, h: 96 } # Master Alt down
    15: { x: 1692, y: 353, w: 600, h: 96 } # Master Bat up
    16: { x: -1, y: -1, w: 600, h: 96 } # Master Bat down
    17: { x: 2292, y: 353, w: 600, h: 96 } # Avionics Bus1 up
    18: { x: -1, y: -1, w: 600, h: 96 } # Avionics Bus1 down
    19: { x: 2892, y: 353, w: 600, h: 96 } # Avionics Bus2 up
    20: { x: -1, y: -1, w: 600, h: 96 } # Avionics Bus2 down
    21: { x: 78, y: 2025, w: 600, h: 96 } # Bcn up
    22: { x: -1, y: -1, w: 600, h: 96 } # Bcn down
    23: { x: 678, y: 2025, w: 600, h: 96 } # Land up
    24: { x: -1, y: -1, w: 600, h: 96 } # Land down
    25: { x: 1278, y: 2025, w: 600, h: 96 } # Taxi up
    26: { x: -1, y: -1, w: 600, h: 96 } # Taxi down
    27: { x: 1878, y: 2025, w: 600, h: 96 } # Nav up
    28: { x: -1, y: -1, w: 600, h: 96 } # Nav down
    29: { x: 2478, y: 2025, w: 600, h: 96 } # Strobe up
    30: { x: -1, y: -1, w: 600, h: 96 } # Strobe down
    31: { x: 3207, y: 1462, w: 600, h: 96 } # Magneto Off
    32: { x: 3207, y: 1562, w: 600, h: 96 } # Magneto Right
    33: { x: 3207, y: 1662, w: 600, h: 96 } # Magneto Left
    34: { x: 3207, y: 1762, w: 600, h: 96 } # Magneto Both
    35: { x: 3207, y: 1862, w: 600, h: 96 } # Magneto Start
    POV1Up: { x: 165, y: 305, w: 800, h: 96 } # PoV hat up
    POV1Right: { x: 165, y: 605, w: 800, h: 96 } # PoV hat right
    POV1Down: { x: 165, y: 505, w: 800, h: 96 } # PoV hat down
    POV1Left: { x: 165, y: 405, w: 800, h: 96 } # PoV hat left
    XAxis: { x: 2289, y: 1762, w: 800, h: 96 } # Yoke rotation
    YAxis: { x: 2289, y: 1862, w: 800, h: 96 } # Yoke pull/push
  SaitekX55Throttle:
    1:     { x: 45,  y: 496, w: 852, h: 54 }
    35:    { x: 104, y: 416, w: 852, h: 54 }
    XAxis: { x: 166, y: 681, w: 570, h: 54 }
    YAxis: { x: 238, y: 588, w: 570, h: 54 }
  ThrustMasterHOTAS4:
    14: { x: -1, y: -1, w: 592, h: 54 } # Does not exist
    15: { x: -1, y: -1, w: 592, h: 108 } # Does not exist
  ThrustMasterHOTASOne:
    1: { x: 1394, y: 614, w: 1082, h: 54 }
    2: { x: 2114, y: 264, w: 1192, h: 54 }
    3: { x: 2954, y: 544, w: 792, h: 108 }
    4: { x: 2754, y: 374, w: 832, h: 108 }
    5: { x: 950, y: 734, w: 592, h: 108 }
    6: { x: 950, y: 898, w: 592, h: 108 }
    7: { x: 950, y: 1046, w: 592, h: 108 }
    8: { x: 1044, y: 1374, w: 592, h: 108 }
    9: { x: 1628, y: 710, w: 832, h: 54 }
    10: { x: 1928, y: 790, w: 532, h: 108 }
    11: { x: 2073, y: 1642, w: 592, h: 108 }
    12: { x: 2192, y: 1785, w: 592, h: 108 }
    13: { x: 284, y: 2044, w: 592, h: 54 }
    14: { x: 984, y: 2044, w: 592, h: 54 }
    15: { x: 1216, y: 1676, w: 592, h: 108 }
    POV1Up: { x: 994, y: 354, w: 1532, h: 54 }
    POV1Right: { x: 994, y: 410, w: 1532, h: 54 }
    POV1Down: { x: 994, y: 466, w: 1532, h: 54 }
    POV1Left: { x: 994, y: 522, w: 1532, h: 54 }
    RZAxis: { x: 3018, y: 1988, w: 792, h: 108 }
    XAxis: { x: 3018, y: 1878, w: 792, h: 108 }
    YAxis: { x: 3018, y: 1768, w: 792, h: 108 }
    ZAxis: { x: 96, y: 736, w: 692, h: 54 }
    UAxis: { x: 1114, y: 1504, w: 932, h: 108 }
  ThrustMasterTFlightHOTASX:
    14: { x: -1, y: -1, w: 592, h: 54 } # Does not exist
    15: { x: -1, y: -1, w: 592, h: 108 } # Does not exist
ImageMap: # Shortname -> image filename
  ThrustMasterHOTASOne : hotasone
  AlphaFlight: alphaflight
DeviceNameMap: # Device Identifier on Windows -> Shortname
  # Airbus T-A320 Quadrant throttle:
  Alpha Flight Controls: AlphaFlight
  # BU0836X Interface:
  # BU0836X Interface_1:
  Joystick - HOTAS Warthog: ThrustMasterWarthogJoystick
  # Keyboard (FSX): # TODO Keyboad
  Logitech Extreme 3D: LogitechExtreme3DPro
  # Mouse: # TODO Mouse
  PS4: DualShock4
  # Saitek Pro Flight Quadrant:
  Saitek Pro Flight Rudder Pedals: SaitekProFlightCombatRudderPedals
  Saitek Pro Flight X-55 Rhino Stick: SaitekX55Joystick
  Saitek Pro Flight X-55 Rhino Throttle: SaitekX55Throttle
  Saitek Pro Flight X-56 Rhino Stick: SaitekX56Joystick
  Saitek Pro Flight X-56 Rhino Throttle: SaitekX56Throttle
  # Saitek Pro Flight Yoke:
  Saitek X52 Flight Control System: SaitekX52
  Saitek X52 Pro Flight Control System: SaitekX52Pro
  T.16000M: T16000M
  # T.A320 CoPilot:
  # T.A320 Pilot:
  T.Flight Hotas 4: ThrustMasterHOTAS4
  T.Flight Hotas One: ThrustMasterHOTASOne
  T.Flight Hotas X: ThrustMasterTFlightHOTASX
  T.Flight Rudder Pedals: T-Rudder
  T.Flight Stick X: 044FB106
  Throttle - HOTAS Warthog: ThrustMasterWarthogThrottle
  TWCS Throttle: T16000MTHROTTLE
  # T-Pendular-Rudder:
  # VF - TPM V3RNIO:
  # VirtualFly - RUDDO+:
  # VirtualFly - TQ3+:
  # VirtualFly - TQ6+:
  # VirtualFly - YOKO+:
  XInput Gamepad: GamePad
DeviceLabelsByImage: # Image filename -> Header label
  alphaflight: "Alpha Flight Controls"
  chcombat: "CH Combatstick & Throttle"
  chfighter: "CH Fighterstick & Throttle"
  chproflightquadrant: "CH Pro Flight Throttle Quadrant"
  chpropedals: "CH Pro Pedals"
  chquadrant: "CH Throttle Quadrant"
  cobram5: "Defender Cobra M5 Stick"
  cougar: "Cougar MFD"
  crosswind: "MFG Crosswind Pedals"
  ds4: "DualShock 4 Controller"
  extreme3dpro: "Extreme 3D Pro"
  f710: "F710 Controller"
  fly5: "Cyborg F.L.Y. 5 Stick"
  g940: "Logitech G940 Pedals"
  g940pedals: "G940 Stick & Throttle"
  gladiator: "VKB Gladiator"
  gtwheel: "Logitech Driving Force GT Wheel"
  hotas4: "T.Flight HOTAS 4 Stick & Throttle"
  hotascougar: "Thrustmaster Hotas Cougar"
  hotasone: "T.Flight HOTAS One Stick & Throttle"
  hotasx: "T.Flight HOTAS X Stick & Throttle"
  keyboard: "Keyboard"
  proflightcombatpedals: "Saitek Pro Flight Combat Pedals"
  proflightpedals: "Saitek Pro Flight Pedals"
  sabretooth: "Sabretooth Controller"
  sidepanelcontroldeck: "Side Panel Control Deck"
  slawbf109pedals: "Slaw BF-109 Pedals"
  stickx: "Thrustmaster T.Flight X Stick"
  t16000m: "T-16000M Stick"
  t16000mfcs: "T.16000M FCS Stick & Throttle"
  tfrp: "Thrustmaster T-Flight Pedals"
  vkb-kosmosima-scg-left: "VKB Kosmosima SCG Left"
  vkb-kosmosima-scg-right: "VKB Kosmosima SCG Right"
  vpc-warbrd-delta-left: "VPC WarBRD DELTA Left"
  vpc-warbrd-delta-right: "VPC WarBRD DELTA Right"
  warthog: "Warthog Stick & Throttle"
  x45: "X-45 Stick & Throttle"
  x52: "X-52 Pro Stick & Throttle"
  x52pro: "X-52 Stick & Throttle"
  x55: "X-55 Stick & Throttle"
  x56: "X-56 Stick & Throttle"
  xbox: "XBox Controller"
  xboxelite: "XBox Elite Controller"
ImageSizeOverride:
  vkb-kosmosima-scg-left: { w: 3879, h: 2182 }
  x45: { w: 5120, h: 2880 }
...