---
Regexes:
  Button: Button\s*(\d+)
  Axis: (?:([R])-)?Axis\s*([XYZ])
  Pov: (?i)Pov(\d?)[\s_]([[:alpha:]]+)
  Rotation: Rotation\s*([XYZ])
  Slider: Slider\s*([XYZ])
DeviceNameMap:
  # Airbus T-A320 Quadrant throttle:
  # Alpha Flight Controls:
  # BU0836X Interface:
  # BU0836X Interface_1:
  Joystick - HOTAS Warthog: ThrustMasterWarthogJoystick
  # Keyboard (FSX): # TODO Keyboad
  Logitech Extreme 3D: LogitechExtreme3DPro
  # Mouse: # TODO Mouse
  PS4: DualShock4
  # Saitek Pro Flight Quadrant:
  Saitek Pro Flight Rudder Pedals: SaitekProFlightCombatRudderPedals
  Saitek Pro Flight X-55 Rhino Stick: SaitekX55Joystick
  Saitek Pro Flight X-55 Rhino Throttle: SaitekX55Throttle
  Saitek Pro Flight X-56 Rhino Stick: SaitekX56Joystick
  Saitek Pro Flight X-56 Rhino Throttle: SaitekX56Throttle
  # Saitek Pro Flight Yoke:
  Saitek X52 Flight Control System: SaitekX52
  Saitek X52 Pro Flight Control System: SaitekX52Pro
  T.16000M: T16000M
  # T.A320 CoPilot:
  # T.A320 Pilot:
  T.Flight Hotas 4: ThrustMasterHOTAS4
  T.Flight Hotas One: ThrustMasterHOTASOne
  T.Flight Hotas X: ThrustMasterTFlightHOTASX
  T.Flight Rudder Pedals: T-Rudder
  T.Flight Stick X: 044FB106
  Throttle - HOTAS Warthog: ThrustMasterWarthogThrottle
  TWCS Throttle: T16000MTHROTTLE
  # T-Pendular-Rudder:
  # VF - TPM V3RNIO:
  # VirtualFly - RUDDO+:
  # VirtualFly - TQ3+:
  # VirtualFly - TQ6+:
  # VirtualFly - YOKO+:
  XInput Gamepad: GamePad
InputMap: # Devices with known game inputs and which model input they map to
  044FB106:
    Slider: { X: U }
  LogitechExtreme3DPro:
    Slider: { X: U }
  SaitekX56Throttle:
    Axis: { RX: RZ, RY: U, RZ: V }
    Slider: { X: RX, Y: RY }
  T16000M:
    Slider: { X: U }
  T16000MFCS:
    Slider: { X: U }
  T16000MTHROTTLE:
    Rotation: { X: X, Y: Y }
    Slider: { X: X, Y: Y }
  ThrustMasterHOTAS4:
    Slider: { X: Z }
  ThrustMasterHOTASOne:
    Slider: { X: Z }
  ThrustMasterTFlightHOTASX:
    Slider: { X: Z }
  ThrustMasterWarthogThrottle:
    Slider: { X: Z }
  T-Rudder:
    Rotation: { X: X, Y: Y }
    Slider: { Y: Z }
InputLabels:
  CHECKLIST : "Display Checklist"
  KEY_ACTIVE_PAUSE_TOGGLE : "Active Pause"
  KEY_AILERON_TRIM_LEFT : "Aileron Trim Left"
  KEY_AILERON_TRIM_RIGHT : "Aileron Trim "
  KEY_ALL_LIGHTS_TOGGLE : "All External Lights"
  KEY_ANTI_ICE_TOGGLE : "Toggle Anti Ice"
  KEY_AP_MASTER : "AutoPilot Master"
  KEY_APU_STARTER : "APU Starter"
  KEY_AXIS_AILERONS_SET : "Ailerons"
  KEY_AXIS_ELEV_TRIM_SET : "Elevator Trim"
  KEY_AXIS_ELEVATOR_SET : "Elevator"
  KEY_AXIS_FLAPS_SET : "Flaps"
  KEY_AXIS_LEFT_BRAKE_SET : "Left Brake"
  KEY_AXIS_MIXTURE_SET : "Mixture"
  KEY_AXIS_RIGHT_BRAKE_SET : "Right Brake"
  KEY_AXIS_RUDDER_SET : "Rudder"
  KEY_BAROMETRIC : "Set Altimeter"
  KEY_BRAKES : "Brakes"
  KEY_CAMERACHASE_RESET : "Reset Ext View"
  KEY_CHASE_FREELOOK_HRZ_SET : "Ext Cam Horizontal"
  KEY_CHASE_FREELOOK_VRTC_SET : "Ext Cam Vertical"
  KEY_CHASE_LOOK_DOWN : "Ext Look Down"
  KEY_CHASE_LOOK_LEFT : "Ext Look Left"
  KEY_CHASE_LOOK_RIGHT : "Ext Look Right"
  KEY_CHASE_LOOK_UP : "Ext Look Up"
  KEY_CHASE_QUICKVIEW1 : "Ext View Left"
  KEY_CHASE_QUICKVIEW2 : "Ext Quickview Down"
  KEY_CHASE_QUICKVIEW3 : "Ext Quickview Right"
  KEY_CHASE_QUICKVIEW4 : "Ext Quickview Up"
  KEY_COCKPIT_BACKCYCLE : "Previous Instrument"
  KEY_COCKPIT_CAMERA_HEIGHT_DEC : "Cockpit Move Down"
  KEY_COCKPIT_CAMERA_HEIGHT_INC : "Cockpit Move Up"
  KEY_COCKPIT_CAMERA_SLIDE_BACK : "Cockpit Move Back"
  KEY_COCKPIT_CAMERA_SLIDE_FRONT : "Cockpit Move Forward"
  KEY_COCKPIT_CAMERA_SLIDE_LEFT : "Cockpit Move Left"
  KEY_COCKPIT_CAMERA_SLIDE_RIGHT : "Cockpit Move Right"
  KEY_COCKPIT_CYCLE : "Next Instrument"
  KEY_COCKPIT_FREELOOK_HRZ_SET : "Cockpit Horiztonal"
  KEY_COCKPIT_FREELOOK_VRTC_SET : "Cockpit Vertical"
  KEY_COCKPIT_INSTR_DOWN : "Instrument View Down"
  KEY_COCKPIT_INSTR_LEFT : "Instrument View Left"
  KEY_COCKPIT_INSTR_RIGHT : "Instrument View Right"
  KEY_COCKPIT_INSTR_UP : "Instrument View Up"
  KEY_COCKPIT_INSTRUMENT1 : "Toggle Instrument View 1"
  KEY_COCKPIT_LOOK_DOWN : "Cockpit Look Down"
  KEY_COCKPIT_LOOK_LEFT : "Cockpit Look Left"
  KEY_COCKPIT_LOOK_RIGHT : "Cockpit Look Right"
  KEY_COCKPIT_LOOK_UP : "Cockpit Look Up"
  KEY_COCKPIT_QUICKVIEW3 : "Cockpit Quickview Right"
  KEY_COCKPIT_QUICKVIEW4 : "Cockpit Quickview Left"
  KEY_COCKPIT_RESET : "Reset Cockpit Cam"
  KEY_COCKPIT_UPPER : "Cockpit Upper"
  KEY_CYCLE_PILOTVIEW_BACK : "Cockpit Prev Pilot"
  KEY_CYCLE_PILOTVIEW_NEXT : "Cockpit Next Pilot"
  KEY_ELEV_TRIM_DN : "Elevator Trim Down"
  KEY_ELEV_TRIM_UP : "Elevator Trim Up"
  KEY_ENGINE : "Select Engine"
  KEY_ENGINE_AUTO_START : "Auto Start Engine"
  KEY_FLAPS_DECR : "Decrease Flaps"
  KEY_FLAPS_DOWN : "Extend Flaps"
  KEY_FLAPS_INCR : "Increase Flaps"
  KEY_FLAPS_UP : "Retract Flaps"
  KEY_GEAR_DOWN : "Landing Gear Down"
  KEY_GEAR_TOGGLE : "Landing Gear"
  KEY_GEAR_UP : "Landing Gear Up"
  KEY_HEADING_GYRO_SET : "Set Heading Indicator"
  KEY_PARKING_BRAKES : "Parking Brake"
  KEY_PAUSE_TOGGLE : "Pause"
  KEY_PROP_PITCH_AXIS_SET_EX1 : "Propeller Pitch"
  KEY_RUDDER_TRIM_LEFT : "Rudder Trim Left"
  KEY_RUDDER_TRIM_RIGHT : "Rudder Trim Right"
  KEY_SHOW_NAVLOG : "Display Navlog"
  KEY_SHOW_VFRMAP : "Display Map"
  KEY_SIM_RATE : "Sim Rate"
  KEY_SIM_RATE_DECR : "Decr Sim Rate"
  KEY_SIM_RATE_INCR : "Incr Sim Rate"
  KEY_SMART_CAMERA_NEXT : "Next Smart Cam Target"
  KEY_SMART_CAMERA_PREVIOUS : "Previous Smart Cam Target"
  KEY_SPOILERS_TOGGLE : "Toggle Spoilers"
  KEY_THROTTLE_AXIS_SET_EX1 : "Throttle"
  KEY_THROTTLE_REVERSE_THRUST_HOLD : "Hold Reverse Thrust"
  KEY_THROTTLE_REVERSE_THRUST_TOGGLE : "Toggle Reverse Thrust"
  KEY_TOGGLE_FEATHER_SWITCHES : "Toggle Feather Switches"
  KEY_TOGGLE_SMART_CAMERA: "Toggle Smart Cam"
  KEY_VIEW_MODE : "Toggle Cockpit/Ext Cam"
  KEY_XPNDR : "Transponder"
  MENU_BACK : "Menu Back"
  MENU_DOWN : "Menu Down"
  MENU_LEFT : "Menu Left"
  MENU_RIGHT : "Menu Right"
  MENU_UP : "Menu Up"
  MENU_VALID : "Menu Select"
  TOGGLE_COPILOT_DELEGATE_CONTROLS : "Delegate to CoPilot"