---
Logo: sws
Regexes:
  Joystick: ^GstInput.JoystickDevice(\d+)(?:\s+(.*))$
  Bind: ^GstKeyBinding\.Incom(Default|Soldier|Starship)InputConcepts\.Concept(.+)\.(\d+)\.(.+)\s+(.+)$
DeviceNameMap:
  Saitek Pro Flight X-55 Rhino Stick: SaitekX55Joystick
  Saitek Pro Flight X-55 Rhino Throttle: SaitekX55Throttle
InputMapping2: # Device -> Axis -> Button
  SaitekX55Joystick:
    8: { Axis: XAxis }
    9: { Axis: YAxis }
    10: { Axis: XAxis }
    11: { Axis: YAxis }
    26: { Button: { 46: RZAxis, 47: RZAxis, 48: POV1Up, 49: POV1Down, 50: POV1Left, 51: POV1Right }}
  SaitekX55Throttle:
    8: { Axis: XAxis }
    9: { Axis: YAxis }
    10: { Axis: XAxis }
    11: { Axis: YAxis }
    26: { Button: { 39: 18, 40: ZAxis, 41: ZAxis, 42: RXAxis, 43: RXAxis, 44: RYAxis, 45: RYAxis, 46: RZAxis, 47: RZAxis,
      64: 19, 65: 20, 69: 24, 70: 25, 71: 26, 72: 27, 73: 28, 74: 29, 75: 30, 76: 31, 80: 35}}
InputOverrides:
InputLabels:
  Afterburner: Boost
  ButtonSelect: Select
  ButtonStart: Menu
  CameraPitch: Pitch
  CameraYaw: Yaw
  CommMenu: Comms Menu
  CommMenuSelect: Comms Select
  Communication: Comms
  ControlBalancePower: Power Balance
  ControlEnginePower: Power Engine Increase
  ControlShieldPower: Power Shield Increase
  ControlWeaponPower: Power Weapon Increase
  ConversationSkip: Skip Conversation
  Deactivate: Deactivate
  Drift: Drift
  Edit: Edit Control
  EmoteWheel: Emote Wheel
  Fire: Fire
  FreeLookCameraDown: Quick Look Down
  FreeLookCameraLeft: Quick Look Left
  FreeLookCameraRight: Quick Look Right
  FreeLookCameraUp: Quick Look Up
  Legend: Legend
  MenuExit: Exit
  PageLeft: Page Left
  ParentNavigateLeft: Tab Left 
  ParentNavigateRight: Tab Right
  PingSelf: Ping Accept
  Pitch: Pitch
  PushTalk: Push-To-Talk
  Ready: Ready
  Roll: Roll
  Scoreboard: Show Loadout
  ScrollDown: Scroll Down
  ScrollUp: Scroll Up
  ShieldBack: Shields To Back
  ShieldBalance: Shields Balance
  ShieldFront: Shields To Front
  SpectatorCameraSwapPlayerMode: Spectator Camera Swap
  SpectatorChangeRestriction: Spectator Change Restriction
  StatusBar: Status Bar
  TargetCycle: Target Cycle
  TargetCycleNext: Target Next
  TargetHighestThreat: Target Attacker
  TargetingMenu: Targetting Menu
  TargetPing: Target Ping
  TargetSelect: Target Select
  Throttle: Throttle
  View: View
  Yaw: Yaw