---
AppName: MetaRef
Version: alpha
DevicesModel: configs/generatedDevices.yaml
FontsDir: resources/fonts
InputFont: Roboto-Regular.ttf
InputFontSize: 40
InputPixelInset: 10
PixelMultiplier: 1.0
ImagesDir: resources/hotas_images
DefaultImageWidth: 3840
DefaultImageHeight: 2160
ImageSizeOverride:
  vkb-kosmosima-scg-left:
    Width: 3879
    Height: 2182
  x45:
    Width: 5120
    Height: 2880
...