---
AppName: MetaRefCard
Version: v0.1
DebugOutput: false
VerboseOutput: false
DevicesModel: configs/generatedDevices.yaml
FontsDir: resources/fonts
InputFont: Roboto-Regular.ttf
InputFontSize: 40
InputPixelInset: 10
PixelMultiplier: 0.4
BackgroundColour: "#e9ecef"
ForegroundColour: "#000000"
# AlternateColours:
#   - #2780e3;
#   - #373a3c;
#   - #3fb618;
#   - #9954bb;
#   - #ff7518;
#   - #ff0039;
#   Light: #f8f9fa;
#   Dark: #373a3c;
#   Blue: #2780e3;
#   Indigo: #6610f2;
#   Purple: #613d7c;
#   Pink: #e83e8c;
#   Red: #ff0039;
#   Orange: #f0ad4e;
#   Yellow: #ff7518;
#   Green: #3fb618;
#   Teal: #20c997;
#   Cyan: #9954bb;
#   White: #fff;
#   Gray: #868e96;
#   Gray-dark: #373a3c;
ImagesDir: resources/hotas_images
DefaultImageWidth: 3840
DefaultImageHeight: 2160
ImageSizeOverride:
  vkb-kosmosima-scg-left:
    Width: 3879
    Height: 2182
  x45:
    Width: 5120
    Height: 2880
...